base_url = "https://resume.alongwy.top"
compile_sass = true
title = "Bartosz Boguszewski"
description = "A clean resume"
generate_feed = false
build_search_index = false
taxonomies = [
  { name = "tags", feed = true },
]

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"

[extra]
first_name = "Bartosz"
last_name = "Boguszewski"
address = "Cracow, Poland"
email = "bartosz.boguszewski@proton.me"
favicon = "/favicon.ico"
avatar = "/media/coffin-nails.png"

katex = false
show_about = true
show_skills = true
show_projects = false
show_opensource = false
show_publications = false
show_experience = true
show_education = false
show_blog = false
