title = "Bartosz Boguszewski"
base_url = "https://bar3nho.github.io"
compile_sass = true
build_search_index = true
default_language = "en"

[markdown]
highlight_code = true

[extra.comment.utterances]
repo = "bar3nho/bar3nho.github.io"
issue_term = "pathname"
theme = "github-dark"

[languages.en]
taxonomies = [
    {name = "tags"},
]

[languages.en.translations]
language_name = "English"
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
date_format = "%Y-%m-%d"
next_page = "Next Page"
last_page = "Last Page"
description = "An unprofessional blog about professional topics."
invitation = "You can find me on:"

[languages.pl.translations]
language_name = "Polski"
about = "Info"
home = "Home"
tags = "Tagi"
archive = "Archiwum"
links = "Linki"
date_format = "%d-%m-%Y"
next_page = "Następna Strona"
last_page = "Poprzednia Strona"
description = "Nieprofesjonalny blog o profesjonalnych zagadnieniach."
invitation = "Możesz mnie znaleźć na:"

[languages.pl]
taxonomies = [
    {name = "tags"},
]

[extra.social]
github = "bar3nho"
twitter = "bar3nho"
instagram = "bartallia"
linkedin = "bar3nho"
stackoverflow = "10071370/bartosz-boguszewski"

[extra]
mode = "dark"

[extra.show]
tags = true
links = true
